import { fetchFilteredMovies, fetchLatestMovies, fetchPopularMovies, fetchSimilairMovies } from "@/app/actions/fetchMovies";
import PopularMovies from "@/app/ui/popularmovies";
import SimilairMovies from "@/app/ui/similairmovies";
import SlickSlider from "@/app/ui/slickslider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LatestPage({ searchParams }: {
    searchParams?: {
        query?: string;
        page?: string;
    };
}) {
  const query = searchParams?.query || '';
  
  const latestMovies = await fetchLatestMovies();
  const popularMovies = await fetchPopularMovies();
  const filteredMovies = await fetchFilteredMovies(query);

  return (
    <>
        <div className="pl-5">
            <h2>Trending</h2>
            {
                query ? (
                    <SlickSlider entertainment={filteredMovies} />
                ) : <SlickSlider entertainment={latestMovies} />
            }
        </div>

        <div className="pl-5 mt-8">
            <h2>Popular Movies</h2>
            <SlickSlider entertainment={popularMovies} />
        </div>
    </>
  );
}
