import { fetchPopularMovies, fetchFilteredMovies } from "@/app/actions/fetchMovies";
import { fetchFilteredTVShows, fetchTvShows } from "@/app/actions/fetchTvShows";
import SlickSlider from "@/app/ui/slickslider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function TvShowsPage({ searchParams }: {
    searchParams?: {
        query?: string;
        page?: string;
    };
}) {
  const query = searchParams?.query || '';

  const tvShows = await fetchTvShows();

  const filteredTVShows = await fetchFilteredTVShows(query);
 
  
  return (
    <>
        <h2 className="pl-5">
            TV Series
        </h2>
        {
            query ? (
                <SlickSlider entertainment={filteredTVShows} />
            ) : <SlickSlider entertainment={tvShows} />
        }
    </>
  );
}
