import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/sidenav";
import Search from "./ui/search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-dark">
            <SideNav />
            <div className="home-section">
              <div className="children">
                <Search placeholder="Enter a movie or tv show..." />
                {children}
              </div>
            </div>
        </div>
      </body>
    </html>
  );
}
