import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MoviesPage() {
  return (
    <h2 className="pl-5">
        Movies
    </h2>
  );
}
